<?php
 $album1 = [

    "Album" => "Fearless (Taylor's Version)",
    "Artista" => "Taylor Swift",
    "No. Regrabacion" => 1,
    "Color Representativo" => "Amarillo",
    "Sencillos" => "Love Story (Taylor's Version), You All Over Me (Taylor's Version)(From The Vault) ,Mr.Perfectly Fine(Taylor's Version)(From The Vault)",
    "Primera Cancion del Album" => "Fearless",
    "Ultima Cancion del Album" => "Bye Bye Baby",
    "Cancion más escuchada" => "You Belong With Me",
    "Disquera" => "Republic Records",
    "Genero" => "Country-Pop",
    "Duración" => 106.20,
    "Canciones 'From The Vault'" => 6,
    "Total de canciones" => 26,
    "Cancion con más duración" => "Untouchable - 5:12 mins",
    "Publicación" => "9 de Abril del 2021",
    "Productores" => "Aaron Dessner, Jack Antonoff, Christopher Rowe y Taylor Swift",
    "Escritores" => "Taylor Swift, Liz Rose, Hillary Lindsey, John Rich, Brad y Brett Warren, Cary y Nathan Barlowe y Tommy Lee James",
    "Formato" => "CD, descarga digital, streaming, Casete, vinilo",
    "Idioma" => "Inglés",
    "No. Billboard 200" => 58,
    "Unidades Equivalentes" => 291000,

 ];
 $album2 = [
    "Album" => "Red (Taylor's Version)",
    "Artista" => "Taylor Swift",
    "No. Regrabacion" => 2,
    "Color Representativo" => "Rojo",
    "Sencillos" => "I Bet You Think About Me (Taylor's Version)(From The Vault), Message in a Bottle (Taylor's Version)(From The Vault)",
    "Sencillos Promocionales" => "All Too Well(10 Minute Version)(Taylor's Version)(From The Vault),Safe & Sound (Taylor's Version), Eyes Open(Taylor's Version)",
    "Primera Cancion del Album" => "State Of Grace (Taylor's Version)",
    "Ultima Cancion del Album" => "Eyes Open (Taylor's Version)",
    "Cancion más escuchada" => 22,
    "Disquera" => "Republic Records",
    "Genero" => "Country, Pop y Rock",
    "Duración" => 138.02,
    "Canciones 'From The Vault'" => 9,
    "Total de canciones" => 32,
    "Cancion con más duración" => " All Too Well (10 Minute Version)(Taylor's Version)(From The Vault) - 10:13 mins",
    "Publicación" => " 12 de noviembre del 2021",
    "Productores" => "Jack Antonoff ,Taylor Swift,Christopher Rowe, Jacknife Lee,Shellback,Dan Wilson,Butch Walker,Mirkovich,Aaron Dessner,Bhasker,Danny D,Tim Blacksmith y Espionage",
    "Escritores" => "Taylor Swift,Liz Rose,Max Martin,Shellback,Dan Wilson,Lightbody,Jacknife Lee,Ed Sheeran,Maya Thompson,Patrick Monahan,Lori McKenna,Mark Foster,Amund Bjørklund y Spen Lind",
    "Formato" => "CD, descarga digital, streaming, Vinilo",
    "Idioma" => "Inglés",
    "No. Billboard 200" => 31,
    "Unidades Equivalentes" => 500000,
    "Reproducciones dia 1" => 9080000000,
 ];
 $album3 = [

    "Album" => "Speak Now (Taylor's Version)",
    "Artista" => "Taylor Swift",
    "No. Regrabacion" => 3,
    "Color Representativo" => "Morado",
    "Sencillo" => "I Can See You (Taylor's Version)(From The Vault)",
    "Primera Cancion del Album" => "Mine",
    "Ultima Cancion del Album" => "Timeless",
    "Cancion más escuchada" => "Enchanted",
    "Disquera" => "Republic Records",
    "Genero" => "Country-Rock",
    "Duración" => 104.33,
    "Canciones 'From The Vault'" => 6,
    "Total de canciones" => 22,
    "Cancion con más duración" => "Dear John - 6:43 mins",
    "Publicación" => "7 de Julio 2023",
    "Productores" => "Aaron Dessner, Jack Antonoff y Taylor Swift",
    "Escritora" => "Taylor Swift",
    "Formato" => "CD, descarga digital, streaming, LP",
    "Idioma" => "Inglés",
    "No. Billboard 200" => 29,
    "Unidades Equivalentes" => 716000,
 ];
 $album4 = [
    "Album" => "1989(Taylor's Version)",
    "Artista" => "Taylor Swift",
    "No. Regrabacion" => 4,
    "Color Representativo" => "Azul Cielo",
    "Sencillos" => " Slut!(Taylor's Version)(From The Vault), Is It Over Now?(Taylor's Version)(From The Vault)",
    "Sencillos Promocionales" => "Wildest Dreams(Taylor's Version), This Love(Taylor's Version)",
    "Primera Cancion del Album" => "Welcome To New York",
    "Ultima Cancion del Album" => "Sweeter Than Fiction",
    "Cancion más escuchada" => "Is It Over Now?(Taylor's Version)(From The Vault)",
    "Disquera" => "Republic Records",
    "Genero" => " Synthpop",
    "Duración" => 77.49,
    "Canciones 'From The Vault'" => 5,
    "Total de canciones" => 22,
    "Cancion con más duración" => " Now That We Don't Talk - 4:39 mins",
    "Publicación" => "27 de Octubre 2023",
    "Productores" => "Taylor Swift,Christopher Rowe,Shellback",
    "Escritores" => "Taylor Swift,Jack Antonoff,Kendrick Lamar,Ryan Tedder,Max Martin,Shellback,Imogen Heap,Ariel Rechtshaid,Diane Warren",
    "Formato" => "CD, descarga digital, streaming, LP, Casete",
    "Idioma" => "Inglés",
    "No. Billboard 200" => 6,
    "Unidades Vendidas" => 1653000,
    "Reproducciones dia 1" => 176000000000,
 ];

 $albums = [
    $album1,
    $album2,
    $album3,
    $album4,
 ];

 echo json_encode($albums);
